config/routes.rb
Rails.application.routes.draw do
  get "async/index"
  post "reactions/create", as: :create_reaction
  post "reactions/destroy", as: :destroy_reaction
  post "comments/create"
  resources :publications
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "publications#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :publication
end

app/models/publication.rb
class Publication < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :reactions, dependent: :destroy
end

app/models/reaction.rb
class Reaction < ApplicationRecord
  belongs_to :user
  belongs_to :publication
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :reactions, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/async_controller.rb
class AsyncController < ApplicationController
  def index
  end

  def algo
    nombre = "Matias"
    edad = 28

    nuevo_div = "<div><ul><li>Nombre: #{nombre}</li><li>Edad: #{edad}</li></ul></div>"
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    # @comment = Comment.new(comment_params)
    # if @comment.save
    #   format.html { redirect_to publications_path, notice: "Comentario creado" }
    # else
    #   format.html { redirect_to publications_path, notice: "Comentario no creado" }
    # end
    content = params[:content]
    publication_id = params[:publication_id]
    @comment
    if current_user != nil
      @comment = Comment.create(content: content, publication_id: publication_id, user: current_user.name)
    else
      @comment = Comment.create(content: content, publication_id: publication_id, user: 'Visita')
    end

    redirect_to publications_path, notice: "Comentario creado"
  end
end

app/controllers/publications_controller.rb
class PublicationsController < ApplicationController
  before_action :set_publication, only: %i[ show edit update destroy ]
  
  # restringimos el acceso a usuarios no auth, excepto para el index y el show
  before_action :authenticate_user!, except: [:index, :show]

  # GET /publications or /publications.json
  def index
    @publications = Publication.all
  end

  # GET /publications/1 or /publications/1.json
  def show
  end

  # GET /publications/new
  def new
    @publication = Publication.new
  end

  # GET /publications/1/edit
  def edit
  end

  # POST /publications or /publications.json
  def create
    @publication = Publication.new(publication_params)
    @publication.user = current_user

    respond_to do |format|
      if @publication.save
        format.html { redirect_to @publication, notice: "Publication was successfully created." }
        format.json { render :show, status: :created, location: @publication }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @publication.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /publications/1 or /publications/1.json
  def update
    respond_to do |format|
      if @publication.update(publication_params)
        format.html { redirect_to @publication, notice: "Publication was successfully updated." }
        format.json { render :show, status: :ok, location: @publication }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @publication.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /publications/1 or /publications/1.json
  def destroy
    @publication.destroy!

    respond_to do |format|
      format.html { redirect_to publications_path, status: :see_other, notice: "Publication was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_publication
      @publication = Publication.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def publication_params
      params.require(:publication).permit(:title, :body)
    end
end

app/controllers/reactions_controller.rb
class ReactionsController < ApplicationController
  before_action :authenticate_user!

  def create
    rtype = params[:rtype]
    publication_id = params[:publication_id]
    publication = Publication.find(publication_id)
    @reaction = publication.reactions.build(rtype: rtype)
    @reaction.user = current_user
    respond_to do |format|
      if @reaction.save
        format.html { redirect_to publication_path(publication_id), notice: "Reaction was successfully created." }
        format.json { render :show, status: :created }
      else
        format.html { redirect_to publication_path(publication_id), notice: "Reaction was NOT created." }
        format.json { render json: {}, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    rtype = params[:rtype]
    publication_id = params[:publication_id]
    publication = Publication.find(publication_id)

    @reactions = Reaction.where(rtype: rtype, publication: publication, user: current_user)
    if @reactions.empty?
      respond_to do |format|
        format.html { redirect_to publication_path(publication_id), notice: "Reaction not found." }
        format.json { render json: {}, status: :not_found }
      end
    else
      @reaction = @reactions.first
      @reaction.destroy
      respond_to do |format|
        format.html { redirect_to publication_path(publication_id), notice: "Reaction was successfully deleted." }
        format.json { head :no_content }
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/async_helper.rb
module AsyncHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/publications_helper.rb
module PublicationsHelper
end

app/helpers/reactions_helper.rb
module ReactionsHelper
end

app/views/async/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Publications" %>

<h1>Publicationes Asíncronas</h1>

<div id="publications">

</div>

<%= link_to "New publication", new_publication_path %>

<script>
  document.addEventListener("DOMContentLoaded", function(event) {
    setTimeout(obtener_publicaciones, 1000);
    //obtener_publicaciones()
  });

  async function obtener_publicaciones() {
    console.log('Obyteniendo publicaciones ...')
    
    const respuesta = await fetch('/publications.json') // AJAX request
    const datos = await respuesta.json()
    
    agregar_publicaciones(datos)
  }

  function agregar_publicaciones(datos) {
    for (publicacion of datos) {
      const div_publicacion = `
        <div id="${publicacion.id}">
          <div class="p-3 publication m-2">
            <div class="row">
              <div class="col-10">
                <p>
                  <strong>Title:</strong>
                  ${publicacion.title}
                </p>

                <p>
                  <strong>Body:</strong>
                  ${publicacion.body}
                </p>
                <p><small>Autor: Autor</small></p>
              </div>
              <div class="col-2">
              
                <div class="text-center reaction">    
                  <a href="/reactions/create?rtype=like&publication_id=4">
                    <i class="bi bi-hand-thumbs-up-fill"></i>
                  </a>
                  <a href="/reactions/destroy?rtype=like&publication_id=2">
                    <i class="bi bi-hand-thumbs-up-fill text-primary"></i>
                  </a>
                  <p>5 likes</p>
                </div>
              </div>
            </div>
          </div>


        </div>
      `
      $('#publications').append(div_publicacion)
    }
  }

</script>

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Crazy4cats" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.css" integrity="sha384-tViUnnbYAV00FLIhhi3v/dWt3Jxw4gZQcNoSCxCIFNJVCx7/D55/wXsrNIRANwdD" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.7.1.min.js" integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>
    <style>
      .publication {
        background-color: #a2d9ce;
        border-radius: 3px;
        border: 2px solid black;
      }
      .comentarios {
        background-color: #bb8fce;
        border-radius: 3px;
        border: 2px solid black;
      }
      .reaction {
        height: 100%;
        vertical-align: bottom;
        color: #999;
      }
      .reaction span {
        color: #999;
        font-size: 2rem;
        cursor: pointer;
      }
      .reaction span:hover {
        color: #666;
      }
    </style>
  </head>

  <body>
    <div class="container">
      <%= render "shared/navbar" %>
      <%= yield %>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>

app/views/publications/_form.html.erb
<%= form_with(model: publication) do |form| %>
  <% if publication.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(publication.errors.count, "error") %> prohibited this publication from being saved:</h2>

      <ul>
        <% publication.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.text_area :body %>
  </div>


  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/publications/_publication.html.erb
<div id="<%= dom_id publication %>">
  <div class="p-3 publication m-2">
    <div class="row">
      <div class="col-10">
        <p>
          <strong>Title:</strong>
          <%= publication.title %>
        </p>

        <p>
          <strong>Body:</strong>
          <%= publication.body %>
        </p>

        <p><small>Autor: <%=publication.user.name%></small></p>
      </div>
      <div class="col-2">
        <div class="text-center reaction">
          <% if user_signed_in? %>
            <% if publication.reactions.where(rtype: "like", user: current_user).count == 0 %>
              <span class="reaction-btn create-reaction" onclick="create_reaction('like', <%=publication.id%>)">
                <i class="bi bi-hand-thumbs-up-fill"></i>
              </span>
              <span class="reaction-btn destroy-reaction d-none" onclick="destroy_reaction('like', <%=publication.id%>)">
                <i class="bi bi-hand-thumbs-up-fill text-primary"></i>
              </span>
            <% else %>
              <span class="reaction-btn create-reaction d-none" onclick="create_reaction('like', <%=publication.id%>)">
                <i class="bi bi-hand-thumbs-up-fill"></i>
              </span>
              <span class="reaction-btn destroy-reaction" onclick="destroy_reaction('like', <%=publication.id%>)">
                <i class="bi bi-hand-thumbs-up-fill text-primary"></i>
              </span>
            <% end %>
          <% end %>
          <p>
            <span class="count">
              <%=publication.reactions.where(rtype: "like").count%>
            </span>
            likes
          </p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/publications/edit.html.erb
<% content_for :title, "Editing publication" %>

<h1>Editing publication</h1>

<%= render "form", publication: @publication %>

<br>

<div>
  <%= link_to "Show this publication", @publication %> |
  <%= link_to "Back to publications", publications_path %>
</div>

app/views/publications/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Publications" %>

<h1>Publications</h1>

<div id="publications">
  <% @publications.each do |publication| %>
    <%= render publication %>
    <p>
      <%= link_to "Show this publication", publication %>
    </p>
  <% end %>
</div>

<%= link_to "New publication", new_publication_path %>

<script>
  const csrf_token = document.querySelector('meta[name="csrf-token"]').content

  async function create_reaction(rtype, publication_id) {

    const respuesta = await fetch('/reactions/create', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'X-CSRF-Token': csrf_token
      },
      body: JSON.stringify({
        rtype: rtype,
        publication_id: publication_id
      }),
    })

    $(`#publication_${publication_id} .reaction span.reaction-btn`).toggleClass('d-none')
    // ahora aumento en 1 el número de likes
    update_num_likes(publication_id, 1)
  }

  function update_num_likes(publication_id, ammount) {
    let num_likes = $(`#publication_${publication_id} span.count`).text()
    num_likes = parseInt(num_likes)
    $(`#publication_${publication_id} span.count`).text(num_likes + ammount)
  }
  
  async function destroy_reaction(rtype, publication_id) {

    const respuesta = await fetch('/reactions/destroy', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'X-CSRF-Token': csrf_token
      },
      body: JSON.stringify({
        rtype: rtype,
        publication_id: publication_id
      }),
    })
    $(`#publication_${publication_id} .reaction span.reaction-btn`).toggleClass('d-none')
    update_num_likes(publication_id, -1)
  }
</script>

app/views/publications/new.html.erb
<% content_for :title, "New publication" %>

<h1>New publication</h1>

<%= render "form", publication: @publication %>

<br>

<div>
  <%= link_to "Back to publications", publications_path %>
</div>

app/views/publications/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @publication %>

<div class="comentarios my-2">
  <div class="row">
    <div class="col-8 offset-2">
      <h4 class="text-center">Comentarios:</h4>

      <%=form_with url: "/comments/create", method: :post do |f| %>
        <%=f.hidden_field :publication_id, value: @publication.id %>
        <div class="m-2">
          <%=f.text_field :content %>
          <%=f.submit "Comenta acá"%>
        </div>
      <% end %>

      <ul class="list-group">
        
        <% @publication.comments.each do |com| %>
          <li class="list-group-item">
            <p><%=com.content%></p>
            <p class="text-right">
              <small>
                <%=com.user%>
              </small>
            </p>
          </li>
        <% end %>

      </ul>
    </div>
  </div>
</div>
<div>
  <%= link_to "Edit this publication", edit_publication_path(@publication) %> |
  <%= link_to "Back to publications", publications_path %>

  <%= button_to "Destroy this publication", @publication, method: :delete %>
</div>

app/views/reactions/create.html.erb
<h1>Reactions#create</h1>
<p>Find me in app/views/reactions/create.html.erb</p>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-dark" data-bs-theme="dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Crazy 4 Catz</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/">Publicaciones</a>
        </li>
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= button_to 'Cerrar sesión', destroy_user_session_path, class:'nav-link', method: :delete %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to 'Iniciar sesión', new_user_session_path, class:'nav-link'%>
          </li>
          <li class="nav-item">
            <%= link_to 'Registro', new_user_registration_path, class:'nav-link'%>
          </li>
      <% end %>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
      </ul>
      <form class="d-flex" role="search">
        <div class="text-light">
          <% if user_signed_in? %>
            Hola <%=current_user.name%>
          <%else%>
            Visita
          <%end%>
        </div>
      </form>
    </div>
  </div>
</nav>